version: '3.8'
services:
  todo-app:
    build: ./
    command: ./todo-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=55fm74rml

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=55fm74rml
    ports:
      - 5436:5432